import type { Branch, Exception, Notification, Technician } from "./types";

const now = Date.now();
const mins = (n: number) => new Date(now + n * 60_000).toISOString();
const hrsAgo = (n: number) => new Date(now - n * 3_600_000).toISOString();

export const workspace = {
  companyName: "Meridian Field Services",
  defaultBranch: "north",
};

export const branches: Branch[] = [
  { id: "north", name: "North Ridge", region: "North", health: "stable" },
  { id: "west", name: "West Harbor", region: "West", health: "high_load" },
  { id: "east", name: "East Meadow", region: "East", health: "critical" },
  { id: "central", name: "Central Yard", region: "North", health: "stable" },
  { id: "south", name: "Southbrook", region: "West", health: "stable" },
  { id: "riverside", name: "Riverside", region: "East", health: "high_load" },
];

export const technicians: Technician[] = [
  {
    id: "marcus",
    name: "Marcus Reyes",
    certifications: ["Refrigeration", "Electrical"],
    minutesAway: 8,
  },
  { id: "dana", name: "Dana Whitfield", certifications: ["Refrigeration"], minutesAway: 22 },
  { id: "priya", name: "Priya Anand", certifications: ["Plumbing", "Boiler"], minutesAway: 14 },
  {
    id: "sam",
    name: "Sam Okafor",
    certifications: ["Electrical", "Access Control"],
    minutesAway: 30,
  },
  {
    id: "lena",
    name: "Lena Kowalski",
    certifications: ["Refrigeration", "Compressor"],
    minutesAway: 40,
  },
];

export const initialExceptions: Exception[] = [
  {
    id: "EX-2041",
    customer: "North Ridge Medical Center",
    issueType: "Walk-in cooler compressor failure",
    issue:
      "Walk-in cooler holding pharmacy stock has climbed to 48°F; site reports compressor cycling.",
    branchId: "north",
    priority: "critical",
    status: "open",
    slaDueAt: mins(42),
    revenueAtRisk: 18400,
    customerHistory: "12 visits in 90 days · 2 prior refrigeration callbacks",
    ownerDispatcher: "Alicia Monroe",
    createdAt: hrsAgo(1.5),
    recommendation: {
      action: "Reassign to Marcus Reyes.",
      quality: "High Confidence",
      signalsCount: 4,
      bullets: [
        "Certified on refrigeration and pharmacy-grade cold chain",
        "8 minutes away from North Ridge",
        "Preserves SLA with 42 min headroom",
        "Avoids overtime approval · Marcus is mid-shift",
      ],
    },
    audit: [
      {
        id: "a1",
        at: hrsAgo(1.5),
        actor: "System",
        actorRole: "system",
        action: "Exception opened from site callback",
      },
      {
        id: "a2",
        at: hrsAgo(1.2),
        actor: "Alicia Monroe",
        actorRole: "dispatcher",
        action: "Triaged priority",
        note: "Pharmacy stock at risk · bumped to Critical.",
      },
      {
        id: "a3",
        at: hrsAgo(0.4),
        actor: "Alicia Monroe",
        actorRole: "dispatcher",
        action: "Attempted assignment to Dana Whitfield",
        note: "Dana declined · 22 min ETA breaches SLA.",
      },
    ],
    favoritedBy: ["dispatcher"],
  },
  {
    id: "EX-2039",
    customer: "Lakeside Grocery Distribution",
    issueType: "Loading dock leveler failure",
    issue:
      "Two of four dock levelers stuck in raised position; inbound trucks holding since 06:20.",
    branchId: "west",
    priority: "critical",
    status: "escalated",
    slaDueAt: mins(-15),
    revenueAtRisk: 26800,
    customerHistory: "Anchor account · 3rd dock incident this quarter",
    ownerDispatcher: "Alicia Monroe",
    createdAt: hrsAgo(3),
    escalation: {
      reason:
        "Need approval to authorize cross-branch transfer of Lena Kowalski from Southbrook · overtime plus travel exceeds branch authority.",
      by: "Alicia Monroe",
      at: hrsAgo(0.5),
    },
    recommendation: {
      action: "Approve cross-branch transfer of Lena Kowalski.",
      quality: "High Confidence",
      signalsCount: 4,
      bullets: [
        "Lena is the only certified compressor tech within a 60 min radius",
        "Cross-branch transfer resolves in one visit vs. two",
        "Overtime cost $340 vs. $6,200 anchor-account exposure",
        "Southbrook queue can absorb · no critical items open",
      ],
    },
    audit: [
      { id: "b1", at: hrsAgo(3), actor: "System", actorRole: "system", action: "Exception opened" },
      {
        id: "b2",
        at: hrsAgo(2.5),
        actor: "Alicia Monroe",
        actorRole: "dispatcher",
        action: "Assigned Priya Anand",
      },
      {
        id: "b3",
        at: hrsAgo(1),
        actor: "Priya Anand",
        actorRole: "system",
        action: "On-site diagnosis",
        note: "Compressor seized · beyond scope; needs Lena.",
      },
      {
        id: "b4",
        at: hrsAgo(0.5),
        actor: "Alicia Monroe",
        actorRole: "dispatcher",
        action: "Escalated to Regional Operations",
        note: "Requesting cross-branch transfer authorization.",
      },
    ],
    favoritedBy: ["dispatcher", "manager"],
  },
  {
    id: "EX-2044",
    customer: "Riverside Office Park",
    issueType: "Rooftop unit · repeat no-heat callback",
    issue:
      "Third heating callback in 30 days on the same rooftop unit; tenant complaints escalating.",
    branchId: "riverside",
    priority: "high",
    status: "escalated",
    slaDueAt: mins(180),
    revenueAtRisk: 4200,
    customerHistory: "Repeat callback · property manager requested credit",
    ownerDispatcher: "Jordan Fields",
    createdAt: hrsAgo(2),
    escalation: {
      reason:
        "Property manager requesting goodwill credit of $1,200 to retain contract. Above branch authority.",
      by: "Jordan Fields",
      at: hrsAgo(0.75),
    },
    recommendation: {
      action: "Approve $800 credit, deny $1,200 ask.",
      quality: "Medium Confidence",
      signalsCount: 4,
      bullets: [
        "Contract renewal in 45 days · retention risk is real",
        "Historical credit ceiling for this account is $800",
        "Full ask sets precedent for other repeat-callback sites",
        "Pair credit with replacement quote to reset expectations",
      ],
    },
    audit: [
      {
        id: "c1",
        at: hrsAgo(2),
        actor: "System",
        actorRole: "system",
        action: "Exception opened from customer call",
      },
      {
        id: "c2",
        at: hrsAgo(1.5),
        actor: "Jordan Fields",
        actorRole: "dispatcher",
        action: "Reviewed callback history",
      },
      {
        id: "c3",
        at: hrsAgo(0.75),
        actor: "Jordan Fields",
        actorRole: "dispatcher",
        action: "Escalated for goodwill credit approval",
      },
    ],
    favoritedBy: ["dispatcher", "manager"],
  },
  {
    id: "EX-2046",
    customer: "Beacon Hill Elementary",
    issueType: "Boiler pressure alarm",
    issue: "Automated pressure alarm from primary boiler; facilities lead unreachable.",
    branchId: "east",
    priority: "critical",
    status: "assigned",
    slaDueAt: mins(28),
    revenueAtRisk: 9600,
    customerHistory: "K–5 school · after-hours alarm protocol active",
    assignedTech: "priya",
    ownerDispatcher: "Alicia Monroe",
    createdAt: hrsAgo(0.75),
    recommendation: {
      action: "Hold Priya on-site; pre-stage relief valve from Central Yard.",
      quality: "High Confidence",
      signalsCount: 3,
      bullets: [
        "Priya has boiler certification and is en route (14 min)",
        "Relief valve inventory confirmed at Central Yard",
        "Pre-staging saves a second truck roll if replacement needed",
      ],
    },
    audit: [
      {
        id: "d1",
        at: hrsAgo(0.75),
        actor: "System",
        actorRole: "system",
        action: "Alarm callback opened",
      },
      {
        id: "d2",
        at: hrsAgo(0.5),
        actor: "Alicia Monroe",
        actorRole: "dispatcher",
        action: "Assigned Priya Anand",
      },
    ],
  },
  {
    id: "EX-2038",
    customer: "Harbor Freight Terminal",
    issueType: "Parts delay · access control",
    issue: "Gate controller replacement backordered 48 hours; site running manual gate coverage.",
    branchId: "west",
    priority: "high",
    status: "open",
    slaDueAt: mins(310),
    revenueAtRisk: 3400,
    customerHistory: "24/7 operation · security-sensitive site",
    ownerDispatcher: "Jordan Fields",
    createdAt: hrsAgo(4),
    recommendation: {
      action: "Offer loaner controller from Central Yard inventory.",
      quality: "Medium Confidence",
      signalsCount: 3,
      bullets: [
        "Central Yard has a compatible loaner unit",
        "Loaner deployment ends manual coverage cost by tonight",
        "Bills at reduced rate · retains customer goodwill",
      ],
    },
    audit: [
      {
        id: "e1",
        at: hrsAgo(4),
        actor: "System",
        actorRole: "system",
        action: "Exception opened · parts ETA slipped",
      },
    ],
  },
  {
    id: "EX-2033",
    customer: "Meridian Corporate Tower",
    issueType: "Elevator inspection overdue",
    issue: "Annual inspection window closes in 60 min; inspector re-scheduled twice.",
    branchId: "central",
    priority: "medium",
    status: "assigned",
    slaDueAt: mins(58),
    revenueAtRisk: 1800,
    customerHistory: "Corporate anchor · compliance-sensitive",
    assignedTech: "sam",
    ownerDispatcher: "Alicia Monroe",
    createdAt: hrsAgo(6),
    recommendation: {
      action: "Confirm inspector arrival at the 60 min mark.",
      quality: "High Confidence",
      signalsCount: 2,
      bullets: [
        "Sam is on-site with inspector escort access",
        "Compliance window closes today · no reschedule buffer",
      ],
    },
    audit: [
      {
        id: "f1",
        at: hrsAgo(6),
        actor: "System",
        actorRole: "system",
        action: "Compliance timer opened",
      },
      {
        id: "f2",
        at: hrsAgo(5),
        actor: "Alicia Monroe",
        actorRole: "dispatcher",
        action: "Assigned Sam Okafor",
      },
    ],
  },
  {
    id: "EX-2029",
    customer: "Pinegrove Assisted Living",
    issueType: "Emergency generator test failure",
    issue: "Monthly load test failed to transfer; facility on utility power only.",
    branchId: "north",
    priority: "high",
    status: "resolved",
    slaDueAt: mins(-240),
    revenueAtRisk: 0,
    customerHistory: "Life-safety site · monthly compliance",
    assignedTech: "marcus",
    ownerDispatcher: "Alicia Monroe",
    createdAt: hrsAgo(28),
    recommendation: {
      action: "Complete transfer switch replacement.",
      quality: "High Confidence",
      signalsCount: 3,
      bullets: ["Root cause identified", "Parts on truck", "Retest scheduled"],
    },
    audit: [
      {
        id: "g1",
        at: hrsAgo(28),
        actor: "System",
        actorRole: "system",
        action: "Exception opened",
      },
      {
        id: "g2",
        at: hrsAgo(26),
        actor: "Marcus Reyes",
        actorRole: "system",
        action: "Repair complete · retest passed",
      },
      {
        id: "g3",
        at: hrsAgo(25),
        actor: "Alicia Monroe",
        actorRole: "dispatcher",
        action: "Resolved",
        note: "Compliance report filed with customer.",
      },
    ],
  },
  {
    id: "EX-2028",
    customer: "Fairmont Plaza Retail",
    issueType: "Rooftop unit refrigerant leak",
    issue: "Confirmed leak on RTU-3; repair completed and system recharged.",
    branchId: "west",
    priority: "medium",
    status: "resolved",
    slaDueAt: mins(-1200),
    revenueAtRisk: 0,
    customerHistory: "Retail center · seasonal load pressure",
    assignedTech: "lena",
    ownerDispatcher: "Jordan Fields",
    createdAt: hrsAgo(48),
    recommendation: {
      action: "Standard repair procedure.",
      quality: "High Confidence",
      signalsCount: 2,
      bullets: ["Leak isolated to Schrader valve", "Parts in stock"],
    },
    audit: [
      {
        id: "h1",
        at: hrsAgo(48),
        actor: "System",
        actorRole: "system",
        action: "Exception opened",
      },
      {
        id: "h2",
        at: hrsAgo(44),
        actor: "Lena Kowalski",
        actorRole: "system",
        action: "Repair complete",
      },
      {
        id: "h3",
        at: hrsAgo(43),
        actor: "Jordan Fields",
        actorRole: "dispatcher",
        action: "Resolved",
      },
    ],
  },
];

// Additional historical decisions surfaced only in the Decisions log.
export const initialDecisionHistory: Exception[] = [
  {
    id: "EX-1998",
    customer: "Cedar Point Distribution",
    issueType: "Cross-branch transfer request",
    issue: "Transfer of certified refrigeration tech for anchor account.",
    branchId: "west",
    priority: "critical",
    status: "approved",
    slaDueAt: hrsAgo(72),
    revenueAtRisk: 22000,
    customerHistory: "Anchor account",
    ownerDispatcher: "Jordan Fields",
    createdAt: hrsAgo(74),
    escalation: {
      reason: "Anchor account cold chain at risk · cross-branch transfer needed.",
      by: "Jordan Fields",
      at: hrsAgo(73),
    },
    decision: {
      outcome: "approved",
      by: "Renata Voss",
      at: hrsAgo(72),
      note: "Approved. Transfer authorized; coordinate with Southbrook lead before dispatch.",
    },
    recommendation: { action: "Approve", quality: "High Confidence", bullets: [], signalsCount: 0 },
    audit: [],
  },
  {
    id: "EX-1994",
    customer: "Bayfront Hotel Group",
    issueType: "Goodwill credit request",
    issue: "Repeat callback on guest-floor rooftop unit; customer requesting $2,500 credit.",
    branchId: "east",
    priority: "high",
    status: "denied",
    slaDueAt: hrsAgo(96),
    revenueAtRisk: 8500,
    customerHistory: "Hospitality group · 4 sites",
    ownerDispatcher: "Alicia Monroe",
    createdAt: hrsAgo(100),
    escalation: {
      reason: "Guest complaints escalating; credit above branch authority.",
      by: "Alicia Monroe",
      at: hrsAgo(97),
    },
    decision: {
      outcome: "denied",
      by: "Renata Voss",
      at: hrsAgo(96),
      note: "Denied at $2,500. Counter with $1,000 credit plus complimentary quarterly PM through year-end.",
    },
    recommendation: {
      action: "Partial credit",
      quality: "Medium Confidence",
      bullets: [],
      signalsCount: 0,
    },
    audit: [],
  },
  {
    id: "EX-1988",
    customer: "Greenfield Logistics",
    issueType: "Overtime authorization",
    issue: "After-hours emergency repair on refrigerated storage.",
    branchId: "north",
    priority: "critical",
    status: "approved",
    slaDueAt: hrsAgo(120),
    revenueAtRisk: 14000,
    customerHistory: "Cold-chain client",
    ownerDispatcher: "Alicia Monroe",
    createdAt: hrsAgo(122),
    escalation: {
      reason: "6 hours of overtime for two technicians to prevent product loss.",
      by: "Alicia Monroe",
      at: hrsAgo(121),
    },
    decision: { outcome: "approved", by: "Renata Voss", at: hrsAgo(120) },
    recommendation: { action: "Approve", quality: "High Confidence", bullets: [], signalsCount: 0 },
    audit: [],
  },
];

export const initialNotifications: Notification[] = [
  {
    id: "n1",
    kind: "escalation",
    message: "Alicia Monroe escalated a cross-branch transfer for Lakeside Grocery.",
    at: hrsAgo(0.5),
    read: false,
    exceptionId: "EX-2039",
    actionLabel: "View escalation",
  },
  {
    id: "n2",
    kind: "sla",
    message: "Beacon Hill Elementary boiler is 28 minutes from SLA breach.",
    at: hrsAgo(0.25),
    read: false,
    exceptionId: "EX-2046",
    actionLabel: "Open details",
  },
  {
    id: "n3",
    kind: "decision",
    message: "Regional Operations approved Greenfield Logistics overtime request.",
    at: hrsAgo(2),
    read: true,
    exceptionId: "EX-1988",
    actionLabel: "Open decision",
  },
  {
    id: "n4",
    kind: "summary",
    message: "Today's roll-up: 8 exceptions, 3 critical open, 2 pending your approval.",
    at: hrsAgo(6),
    read: true,
    actionLabel: "Dismiss",
  },
  {
    id: "n5",
    kind: "customer_stub",
    message: "Customer SMS to North Ridge Medical Center is stubbed for this prototype.",
    at: hrsAgo(0.75),
    read: true,
    exceptionId: "EX-2041",
    actionLabel: "Dismiss",
  },
  {
    id: "n6",
    kind: "escalation",
    message: "Jordan Fields escalated a goodwill credit request for Riverside Office Park.",
    at: hrsAgo(0.75),
    read: false,
    exceptionId: "EX-2044",
    actionLabel: "View escalation",
  },
  {
    id: "n7",
    kind: "sla",
    message: "North Ridge Medical Center compressor is inside the 60 min SLA window.",
    at: hrsAgo(0.15),
    read: false,
    exceptionId: "EX-2041",
    actionLabel: "Open details",
  },
  {
    id: "n8",
    kind: "decision",
    message: "Regional Operations denied Bayfront Hotel Group credit request.",
    at: hrsAgo(4),
    read: true,
    exceptionId: "EX-1994",
    actionLabel: "Open decision",
  },
];

export const favoritesList = ["EX-2041", "EX-2039", "EX-2044"];
