/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppManagerRouteImport } from './routes/_app.manager'
import { Route as AppDispatcherRouteImport } from './routes/_app.dispatcher'
import { Route as AppManagerIndexRouteImport } from './routes/_app.manager.index'
import { Route as AppDispatcherIndexRouteImport } from './routes/_app.dispatcher.index'
import { Route as AppManagerTodayRouteImport } from './routes/_app.manager.today'
import { Route as AppManagerEscalationsRouteImport } from './routes/_app.manager.escalations'
import { Route as AppManagerDecisionsRouteImport } from './routes/_app.manager.decisions'
import { Route as AppDispatcherTodayRouteImport } from './routes/_app.dispatcher.today'
import { Route as AppDispatcherResolvedRouteImport } from './routes/_app.dispatcher.resolved'
import { Route as AppDispatcherAssignmentsRouteImport } from './routes/_app.dispatcher.assignments'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagerRoute = AppManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatcherRoute = AppDispatcherRouteImport.update({
  id: '/dispatcher',
  path: '/dispatcher',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerIndexRoute = AppManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppDispatcherIndexRoute = AppDispatcherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDispatcherRoute,
} as any)
const AppManagerTodayRoute = AppManagerTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerEscalationsRoute = AppManagerEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerDecisionsRoute = AppManagerDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppDispatcherTodayRoute = AppDispatcherTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppDispatcherRoute,
} as any)
const AppDispatcherResolvedRoute = AppDispatcherResolvedRouteImport.update({
  id: '/resolved',
  path: '/resolved',
  getParentRoute: () => AppDispatcherRoute,
} as any)
const AppDispatcherAssignmentsRoute =
  AppDispatcherAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AppDispatcherRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dispatcher': typeof AppDispatcherRouteWithChildren
  '/manager': typeof AppManagerRouteWithChildren
  '/dispatcher/assignments': typeof AppDispatcherAssignmentsRoute
  '/dispatcher/resolved': typeof AppDispatcherResolvedRoute
  '/dispatcher/today': typeof AppDispatcherTodayRoute
  '/manager/decisions': typeof AppManagerDecisionsRoute
  '/manager/escalations': typeof AppManagerEscalationsRoute
  '/manager/today': typeof AppManagerTodayRoute
  '/dispatcher/': typeof AppDispatcherIndexRoute
  '/manager/': typeof AppManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dispatcher/assignments': typeof AppDispatcherAssignmentsRoute
  '/dispatcher/resolved': typeof AppDispatcherResolvedRoute
  '/dispatcher/today': typeof AppDispatcherTodayRoute
  '/manager/decisions': typeof AppManagerDecisionsRoute
  '/manager/escalations': typeof AppManagerEscalationsRoute
  '/manager/today': typeof AppManagerTodayRoute
  '/dispatcher': typeof AppDispatcherIndexRoute
  '/manager': typeof AppManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dispatcher': typeof AppDispatcherRouteWithChildren
  '/_app/manager': typeof AppManagerRouteWithChildren
  '/_app/dispatcher/assignments': typeof AppDispatcherAssignmentsRoute
  '/_app/dispatcher/resolved': typeof AppDispatcherResolvedRoute
  '/_app/dispatcher/today': typeof AppDispatcherTodayRoute
  '/_app/manager/decisions': typeof AppManagerDecisionsRoute
  '/_app/manager/escalations': typeof AppManagerEscalationsRoute
  '/_app/manager/today': typeof AppManagerTodayRoute
  '/_app/dispatcher/': typeof AppDispatcherIndexRoute
  '/_app/manager/': typeof AppManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dispatcher'
    | '/manager'
    | '/dispatcher/assignments'
    | '/dispatcher/resolved'
    | '/dispatcher/today'
    | '/manager/decisions'
    | '/manager/escalations'
    | '/manager/today'
    | '/dispatcher/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dispatcher/assignments'
    | '/dispatcher/resolved'
    | '/dispatcher/today'
    | '/manager/decisions'
    | '/manager/escalations'
    | '/manager/today'
    | '/dispatcher'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dispatcher'
    | '/_app/manager'
    | '/_app/dispatcher/assignments'
    | '/_app/dispatcher/resolved'
    | '/_app/dispatcher/today'
    | '/_app/manager/decisions'
    | '/_app/manager/escalations'
    | '/_app/manager/today'
    | '/_app/dispatcher/'
    | '/_app/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/manager': {
      id: '/_app/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AppManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dispatcher': {
      id: '/_app/dispatcher'
      path: '/dispatcher'
      fullPath: '/dispatcher'
      preLoaderRoute: typeof AppDispatcherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/': {
      id: '/_app/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof AppManagerIndexRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/dispatcher/': {
      id: '/_app/dispatcher/'
      path: '/'
      fullPath: '/dispatcher/'
      preLoaderRoute: typeof AppDispatcherIndexRouteImport
      parentRoute: typeof AppDispatcherRoute
    }
    '/_app/manager/today': {
      id: '/_app/manager/today'
      path: '/today'
      fullPath: '/manager/today'
      preLoaderRoute: typeof AppManagerTodayRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/escalations': {
      id: '/_app/manager/escalations'
      path: '/escalations'
      fullPath: '/manager/escalations'
      preLoaderRoute: typeof AppManagerEscalationsRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/decisions': {
      id: '/_app/manager/decisions'
      path: '/decisions'
      fullPath: '/manager/decisions'
      preLoaderRoute: typeof AppManagerDecisionsRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/dispatcher/today': {
      id: '/_app/dispatcher/today'
      path: '/today'
      fullPath: '/dispatcher/today'
      preLoaderRoute: typeof AppDispatcherTodayRouteImport
      parentRoute: typeof AppDispatcherRoute
    }
    '/_app/dispatcher/resolved': {
      id: '/_app/dispatcher/resolved'
      path: '/resolved'
      fullPath: '/dispatcher/resolved'
      preLoaderRoute: typeof AppDispatcherResolvedRouteImport
      parentRoute: typeof AppDispatcherRoute
    }
    '/_app/dispatcher/assignments': {
      id: '/_app/dispatcher/assignments'
      path: '/assignments'
      fullPath: '/dispatcher/assignments'
      preLoaderRoute: typeof AppDispatcherAssignmentsRouteImport
      parentRoute: typeof AppDispatcherRoute
    }
  }
}

interface AppDispatcherRouteChildren {
  AppDispatcherAssignmentsRoute: typeof AppDispatcherAssignmentsRoute
  AppDispatcherResolvedRoute: typeof AppDispatcherResolvedRoute
  AppDispatcherTodayRoute: typeof AppDispatcherTodayRoute
  AppDispatcherIndexRoute: typeof AppDispatcherIndexRoute
}

const AppDispatcherRouteChildren: AppDispatcherRouteChildren = {
  AppDispatcherAssignmentsRoute: AppDispatcherAssignmentsRoute,
  AppDispatcherResolvedRoute: AppDispatcherResolvedRoute,
  AppDispatcherTodayRoute: AppDispatcherTodayRoute,
  AppDispatcherIndexRoute: AppDispatcherIndexRoute,
}

const AppDispatcherRouteWithChildren = AppDispatcherRoute._addFileChildren(
  AppDispatcherRouteChildren,
)

interface AppManagerRouteChildren {
  AppManagerDecisionsRoute: typeof AppManagerDecisionsRoute
  AppManagerEscalationsRoute: typeof AppManagerEscalationsRoute
  AppManagerTodayRoute: typeof AppManagerTodayRoute
  AppManagerIndexRoute: typeof AppManagerIndexRoute
}

const AppManagerRouteChildren: AppManagerRouteChildren = {
  AppManagerDecisionsRoute: AppManagerDecisionsRoute,
  AppManagerEscalationsRoute: AppManagerEscalationsRoute,
  AppManagerTodayRoute: AppManagerTodayRoute,
  AppManagerIndexRoute: AppManagerIndexRoute,
}

const AppManagerRouteWithChildren = AppManagerRoute._addFileChildren(
  AppManagerRouteChildren,
)

interface AppRouteChildren {
  AppDispatcherRoute: typeof AppDispatcherRouteWithChildren
  AppManagerRoute: typeof AppManagerRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDispatcherRoute: AppDispatcherRouteWithChildren,
  AppManagerRoute: AppManagerRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
